In [3]:
import pandas as pd

url = 'https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'
df=pd.read_csv(url)
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [4]:
#check number of rows and columns in dataset
df.shape

(150, 5)

In [12]:
#create a dataframe with all training data except the target column
X = df.drop(columns=["petal.length"])
#check that the target variable has been removed
X.head()

   sepal.length  sepal.width  petal.width variety
0           5.1          3.5          0.2  Setosa
1           4.9          3.0          0.2  Setosa
2           4.7          3.2          0.2  Setosa
3           4.6          3.1          0.2  Setosa
4           5.0          3.6          0.2  Setosa

In [13]:
#separate target values
y = df["petal.length"].values
#view target values
y[0:5]

array([1.4, 1.4, 1.3, 1.5, 1.4])

In [16]:
from sklearn.model_selection import train_test_split
#split dataset into train and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1, stratify=y)

ValueError: ignored